//! Platform error type.
//!
//! [`PlatformError`] is the single error enum for the tenancy, feature-flag, and
//! audit concerns in this crate. Its `category()` / `code()` impl is generated by
//! the [`DomainError`](klauthed_error::DomainError) derive, so every variant maps
//! to a stable `platform.<reason>` code and an [`ErrorCategory`].
//!
//! [`ErrorCategory`]: klauthed_error::ErrorCategory

mod platform_error;

pub use platform_error::*;
